// routes/sections.js
import express from 'express';
import Section from '../models/section.js';
import User from '../models/user.js';
import { protect, adminOnly } from '../middleware/auth.js';

const router = express.Router();

// All routes require admin authentication
router.use(protect);
router.use(adminOnly);

// @route   GET /api/sections
// @desc    Get all sections
// @access  Admin only
router.get('/', async (req, res) => {
  try {
    const sections = await Section.find()
      .populate('students', 'fullName email role')
      .sort({ department: 1, yearLevel: 1, name: 1 });

    res.json(sections);
  } catch (error) {
    console.error('Get sections error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   GET /api/sections/:id
// @desc    Get single section with students
// @access  Admin only
router.get('/:id', async (req, res) => {
  try {
    const section = await Section.findById(req.params.id)
      .populate('students', 'fullName email role createdAt');

    if (!section) {
      return res.status(404).json({ message: 'Section not found' });
    }

    res.json(section);
  } catch (error) {
    console.error('Get section error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   POST /api/sections
// @desc    Create new section
// @access  Admin only
router.post('/', async (req, res) => {
  try {
    const { department, yearLevel, sectionNumber } = req.body;

    // Check if this dept/year/section combination already exists
    const existingSection = await Section.findOne({ 
      department, 
      yearLevel, 
      sectionNumber 
    });
    
    if (existingSection) {
      return res.status(400).json({ 
        message: `Section ${department} ${yearLevel}-${sectionNumber} already exists` 
      });
    }

    const section = await Section.create({
      department,
      yearLevel,
      sectionNumber,
      students: [],
      createdBy: req.user._id
      // name will be auto-generated by pre-save hook
    });

    res.status(201).json({
      success: true,
      message: 'Section created successfully',
      data: section
    });
  } catch (error) {
    console.error('Create section error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   PUT /api/sections/:id
// @desc    Update section
// @access  Admin only
router.put('/:id', async (req, res) => {
  try {
    const { department, yearLevel, sectionNumber, isActive } = req.body;

    const section = await Section.findById(req.params.id);

    if (!section) {
      return res.status(404).json({ message: 'Section not found' });
    }

    // Check if new combination conflicts with existing section
    if (department !== section.department || 
        yearLevel !== section.yearLevel || 
        sectionNumber !== section.sectionNumber) {
      
      const existingSection = await Section.findOne({ 
        department,
        yearLevel,
        sectionNumber,
        _id: { $ne: req.params.id } 
      });
      
      if (existingSection) {
        return res.status(400).json({ 
          message: `Section ${department} ${yearLevel}-${sectionNumber} already exists` 
        });
      }
    }

    section.department = department;
    section.yearLevel = yearLevel;
    section.sectionNumber = sectionNumber;
    if (isActive !== undefined) section.isActive = isActive;
    // name will be auto-updated by pre-save hook

    await section.save();

    res.json({
      success: true,
      message: 'Section updated successfully',
      data: section
    });
  } catch (error) {
    console.error('Update section error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   DELETE /api/sections/:id
// @desc    Delete section
// @access  Admin only
router.delete('/:id', async (req, res) => {
  try {
    const section = await Section.findById(req.params.id);

    if (!section) {
      return res.status(404).json({ message: 'Section not found' });
    }

    // Check if section has students
    if (section.students.length > 0) {
      return res.status(400).json({ 
        message: `Cannot delete section with ${section.students.length} students. Remove students first.` 
      });
    }

    await section.deleteOne();

    res.json({ 
      success: true,
      message: 'Section deleted successfully' 
    });
  } catch (error) {
    console.error('Delete section error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   POST /api/sections/:id/students
// @desc    Add students to section
// @access  Admin only
router.post('/:id/students', async (req, res) => {
  try {
    const { studentIds } = req.body; // Array of student IDs

    const section = await Section.findById(req.params.id);

    if (!section) {
      return res.status(404).json({ message: 'Section not found' });
    }

    // Verify all IDs are valid students
    const students = await User.find({
      _id: { $in: studentIds },
      userType: 'student'
    });

    if (students.length !== studentIds.length) {
      return res.status(400).json({ 
        message: 'One or more invalid student IDs' 
      });
    }

    // Add students to section (avoid duplicates)
    const newStudents = studentIds.filter(
      id => !section.students.includes(id)
    );
    
    section.students.push(...newStudents);
    await section.save();

    // Update student records to reference this section
    await User.updateMany(
      { _id: { $in: newStudents } },
      { section: section._id }
    );

    res.json({
      success: true,
      message: `${newStudents.length} students added to section`,
      data: section
    });
  } catch (error) {
    console.error('Add students error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

// @route   DELETE /api/sections/:id/students/:studentId
// @desc    Remove student from section
// @access  Admin only
router.delete('/:id/students/:studentId', async (req, res) => {
  try {
    const section = await Section.findById(req.params.id);

    if (!section) {
      return res.status(404).json({ message: 'Section not found' });
    }

    // Remove student from section
    section.students = section.students.filter(
      id => id.toString() !== req.params.studentId
    );
    
    await section.save();

    // Remove section reference from student
    await User.findByIdAndUpdate(
      req.params.studentId,
      { $unset: { section: 1 } }
    );

    res.json({
      success: true,
      message: 'Student removed from section',
      data: section
    });
  } catch (error) {
    console.error('Remove student error:', error);
    res.status(500).json({ message: 'Server error' });
  }
});

export default router;